// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20191101210830_UpdateSeedData")]
    partial class UpdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("Rating");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("StateOrNational")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Activities = "Trail running, birdwatching",
                            Name = "SamuelPTaylor",
                            Rating = 10,
                            State = "CA",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 2,
                            Activities = "Snowshoeing, snowman-building",
                            Name = "Denali",
                            Rating = 10,
                            State = "AK",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Activities = "Hiking, picnicking",
                            Name = "Grand Canyon",
                            Rating = 4,
                            State = "AZ",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Activities = "Rock-climbing",
                            Name = "Joshua Tree",
                            Rating = 10,
                            State = "CA",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Activities = "Fishing, swimming, trail-running",
                            Name = "Lake Tahoe",
                            Rating = 9,
                            State = "NV",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Activities = "Hiking, running, mountaineering",
                            Name = "Rocky Mounatin",
                            Rating = 5,
                            State = "CO",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 7,
                            Activities = "Backpacking, hiking",
                            Name = "Yellowstone",
                            Rating = 2,
                            State = "ID",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 8,
                            Activities = "Coconut-hunting, cycling",
                            Name = "Haleakala",
                            Rating = 8,
                            State = "HI",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Activities = "Running, bat-watching",
                            Name = "Mammoth Cave",
                            Rating = 6,
                            State = "KY",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 10,
                            Activities = "Trekking, kayaking",
                            Name = "Glacier",
                            Rating = 10,
                            State = "MT",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 11,
                            Activities = "Rock-climbing, hiking,",
                            Name = "Goblin Valley",
                            Rating = 10,
                            State = "UT",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 12,
                            Activities = "Hiking, sun-bathing",
                            Name = "Arches",
                            Rating = 10,
                            State = "UT",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 13,
                            Activities = "Trail running, hiking",
                            Name = "BadLands",
                            Rating = 9,
                            State = "SD",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 14,
                            Activities = "Hiking, exploring",
                            Name = "Bryce Canyon",
                            Rating = 10,
                            State = "UT",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 15,
                            Activities = "Hiking, walking, squeezing",
                            Name = "Carlsbad Caverns",
                            Rating = 8,
                            State = "NM",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 16,
                            Activities = "Trail running, mountain-ogling",
                            Name = "Grand Teton",
                            Rating = 3,
                            State = "WY",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 17,
                            Activities = "Running, walking, crawling",
                            Name = "Congaree",
                            Rating = 7,
                            State = "SC",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 18,
                            Activities = "Boating, hiking, picnicking",
                            Name = "Crater Lake",
                            Rating = 10,
                            State = "OR",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 19,
                            Activities = "Mountaineering, skyrunning",
                            Name = "Great Smoky Mountains",
                            Rating = 9,
                            State = "TN",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 20,
                            Activities = "Sight-seeing, picnicking",
                            Name = "Guadalupe Mountains",
                            Rating = 7,
                            State = "TX",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 21,
                            Activities = "Trekking, waterfalls",
                            Name = "Voyageurs",
                            Rating = 8,
                            State = "MN",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 22,
                            Activities = "Swimming, walking, cartwheeling",
                            Name = "Big Creek",
                            Rating = 7,
                            State = "IA",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 23,
                            Activities = "Trail running, camping",
                            Name = "Cheboygan",
                            Rating = 9,
                            State = "MI",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 24,
                            Activities = "Mountain biking, hiking, sunset-viewing",
                            Name = "Joaquin Miller",
                            Rating = 10,
                            State = "CA",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 25,
                            Activities = "Running, bird-watching",
                            Name = "Carlsbad Caverns",
                            Rating = 8,
                            State = "NM",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 26,
                            Activities = "Running, hiking, climbing, swimming",
                            Name = "Zion",
                            Rating = 10,
                            State = "UT",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 27,
                            Activities = "Mountaineering, hiking",
                            Name = "Arrowhead",
                            Rating = 7,
                            State = "OK",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 28,
                            Activities = "Rock-climbing, camping",
                            Name = "Tombigbee",
                            Rating = 6,
                            State = "MS",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 29,
                            Activities = "Cycling, camping, bird-watching",
                            Name = "Little Missouri",
                            Rating = 8,
                            State = "MO",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 30,
                            Activities = "Mountain biking, backpacking",
                            Name = "Shenandoah",
                            Rating = 8,
                            State = "VA",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 31,
                            Activities = "Cycling, canoeing",
                            Name = "DeSoto",
                            Rating = 2,
                            State = "AL",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 32,
                            Activities = "Swimming, clam digging",
                            Name = "Acadia",
                            Rating = 7,
                            State = "ME",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 33,
                            Activities = "Mushroom foraging, hiking",
                            Name = "Biscayne",
                            Rating = 5,
                            State = "FL",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 34,
                            Activities = "Trekking, camping",
                            Name = "Cuyahoga Valley",
                            Rating = 4,
                            State = "OH",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 35,
                            Activities = "Plogging, skyrunning",
                            Name = "Everglades",
                            Rating = 7,
                            State = "FL",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 36,
                            Activities = "Running, bird-watching",
                            Name = "Oak Mountain",
                            Rating = 6,
                            State = "AL",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 37,
                            Activities = "Canyoning, Skiing, hiking",
                            Name = "Borderland",
                            Rating = 8,
                            State = "MA",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 38,
                            Activities = "Trail running, birdwatching, paragliding",
                            Name = "Burlingame",
                            Rating = 9,
                            State = "RI",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 39,
                            Activities = "Fly fishing, kayaking",
                            Name = "Camel's Hump",
                            Rating = 10,
                            State = "VT",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 40,
                            Activities = "Rappelling, hiking",
                            Name = "Green River Resevoir",
                            Rating = 3,
                            State = "VT",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 41,
                            Activities = "Skiing, snowshoeing",
                            Name = "Gates of the Arctic",
                            Rating = 10,
                            State = "AK",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 42,
                            Activities = "Camping, backpacking, train running",
                            Name = "Great Basin",
                            Rating = 6,
                            State = "NV",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 43,
                            Activities = "Mountain biking, rock climbing",
                            Name = "Great Sand Dunes",
                            Rating = 9,
                            State = "CO",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 44,
                            Activities = "Clam digging, swimming, sailing",
                            Name = "High Falls",
                            Rating = 6,
                            State = "GA",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 45,
                            Activities = "Windsurfing, birdwatching",
                            Name = "Isle Royale",
                            Rating = 7,
                            State = "MI",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 46,
                            Activities = "Ice climbing, running, birdwatching",
                            Name = "Katmai",
                            Rating = 8,
                            State = "AK",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 47,
                            Activities = "Trekking, running, hiking",
                            Name = "Olympic",
                            Rating = 10,
                            State = "WA",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 48,
                            Activities = "Mushroom foraging, plogging, tree climbing",
                            Name = "Petrified Forest",
                            Rating = 9,
                            State = "AZ",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 49,
                            Activities = "Paragliding, wingsuit flying",
                            Name = "Wind Cave",
                            Rating = 3,
                            State = "SD",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 50,
                            Activities = "Motorbike expedition, sightseeing",
                            Name = "Indiana Dunes",
                            Rating = 4,
                            State = "IN",
                            StateOrNational = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
