// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20191101164235_FirstSeedData")]
    partial class FirstSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Rating");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("StateOrNational")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Samuel P. Taylor",
                            Rating = 10,
                            State = "CA",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Denali",
                            Rating = 10,
                            State = "AK",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Grand Canyon",
                            Rating = 9,
                            State = "AZ",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Joshua Tree",
                            Rating = 10,
                            State = "CA",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Lake Tahoe",
                            Rating = 10,
                            State = "NV",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Rocky Mounatin",
                            Rating = 10,
                            State = "CO",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Yellowstone",
                            Rating = 10,
                            State = "ID",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Haleakala",
                            Rating = 8,
                            State = "HI",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Mammoth Cave",
                            Rating = 10,
                            State = "KY",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 10,
                            Name = "Glacier",
                            Rating = 10,
                            State = "MT",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 11,
                            Name = "Goblin Valley",
                            Rating = 10,
                            State = "UT",
                            StateOrNational = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
